version: '3.7'
services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run start
        container_name: app
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/app
            - /app/node_modules